### ISSUE TITLE
Polish translation

### ISSUE THREAD

**Issue by badyl00** [andi34/photobooth#110]
**Missing language**
Polish

**Additional context**

**Comment by andi34** [comment]
https://crowdin.com/project/photobooth/pl#

Please join as Translator.

Thanks for your request ☺️

**Comment by andi34** [comment]
Will be added once translation is at least 70% completed.
If you have questions please let me know. Thanks a lot for your contribution!

**Comment by badyl00** [comment]
I added translations. All of it its made on computer and must check it on
working hardware (raspberry). It is possibile to emulate aplication on
computer (windows) to check translations and functions ? I don't know if Polish characters will be displayed correctly. Thanks.

**Comment by andi34** [comment]
Hey!
Thanks a lot! Will take a look at it later this week.
I can send you a zip with it included if you like. ~~On windows there might be an issue because of simple-translator having an `@` in the path, need to investigate. In general~~ You can also setup an apache Webserver with php enabled on Windows.

https://youtu.be/5Ta1NE1ugqE

**Comment by andi34** [comment]
![Screenshot_2020-09-27_09-18-00](https://user-images.githubusercontent.com/6080900/94358587-799d8380-00a2-11eb-8b32-69ae13febc72.png)

![Screenshot_2020-09-27_09-17-38](https://user-images.githubusercontent.com/6080900/94358588-7aceb080-00a2-11eb-966a-780ffa09528f.png)

![Screenshot_2020-09-27_09-17-13](https://user-images.githubusercontent.com/6080900/94358589-7b674700-00a2-11eb-8ee3-f0d2bcf64c0e.png)
