### ISSUE TITLE
[BUG]: gphoto2 livepreview during collage

### ISSUE THREAD

**Issue by crazylenni** [andi34/photobooth#412]
### Describe the bug

Hi, I got the live preview from a gphoto2 device running as a background and as a live preview. While I take a collage during the photos no live preview is shown anymore.

### Steps to reproduce the behavior

Click on "capture collage"
Preview before picture taking is missing

### Expected behavior

live preview available before each photo (collage)

### Photobooth Version

v3.3.0

### Browser and browser version

chromium 98.0.4758.106

### Operating System

Debian GNU/Linux 11 (bullseye)

### Did it work before?

No

**Comment by andi34** [comment]
First of all you should update to latest dev version.
You also should disable BSM or use a longer countdown. It's a hardware limitation and works smother on better hardware (Pi only has limited resources). Getting the preview visible takes up to 5 seconds but need to be stopped 2-3 seconds before the countdown ends to free gohoto to be able to take a picture.
On latest dev version you can also use Python-gphoto for preview and to take pictures which will allow shorter countdown, because preview doesn't need to be killed to free gohoto on that:
https://github.com/andi34/photobooth/blob/dev/faq/faq.md#how-to-get-better-performance-using-gphoto2-as-preview
